language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      before_install:
        - wget --no-check-certificate https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
        - sudo dpkg -i cvmfs-release-latest_all.deb
        - sudo apt-get update
        - sudo apt-get install cvmfs cvmfs-config-default
        - rm -f cvmfs-release-latest_all.deb
        - wget --no-check-certificate https://lcd-data.web.cern.ch/lcd-data/CernVM/default.local
        - sudo mkdir -p /etc/cvmfs
        - sudo mv default.local /etc/cvmfs/default.local
        - sudo /etc/init.d/autofs stop
        - sudo cvmfs_config setup
        # - sudo mkdir -p /cvmfs/sft.cern.ch
        # - sudo mount -t cvmfs sft.cern.ch /cvmfs/sft.cern.ch
        - ls /cvmfs/sft.cern.ch
      services:
        - docker
      script:
        - docker run -ti --name CI_container -v ${PWD}:/src -w /src -v"/cvmfs:/cvmfs:ro" -v"$PWD/.travis/cc7_lcg96.sh:/entrypoint.sh:ro" -d gitlab-registry.cern.ch/acts/machines/cc7 /entrypoint.sh
