language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
addons:
        apt:
          packages:
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - libeigen3-dev
      - boost1.67
      - cmake

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install eigen ; fi

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_CXX_STANDARD=17 -DACTS_BUILD_EXAMPLES=on -DACTS_BUILD_TESTS=on -DACTS_BUILD_INTEGRATION_TESTS=on -DACTS_BUILD_DIGITIZATION_PLUGIN=on -DACTS_BUILD_IDENTIFICATION_PLUGIN=on -DACTS_BUILD_JSON_PLUGIN=on -DACTS_BUILD_LEGACY=on
  - VERBOSE=1 make -j$(nproc)




