name: checks

on: [push]

jobs:
  license:
    runs-on: gitlab-registry.cern.ch/acts/machines/check_llvm8:latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: CI/check_format . 

