name: checks

on: [push]

jobs:
  format:
    runs-on: ubuntu-18.04
    container: gitlab-registry.cern.ch/acts/machines/check_llvm8:latest
    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: CI/check_format .
  license:
    runs-on: ubuntu-18.04
    container: python:alpine3.6
    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: >
        apk add --no-cache git
        && CI/check_license.py . --exclude "*thirdparty/*"
  include_guards:
    runs-on: ubuntu-18.04
    container: python:alpine3.6
    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: >
        CI/check_include_guards.py . --fail-global --exclude "*thirdparty/*"

  build:
    runs-on: ubuntu-18.04
    container: gitlab-registry.cern.ch/acts/machines/ubuntu1910
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: >
        mkdir build && cd build
        && cmake ..
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_CXX_STANDARD=17
        -DACTS_BUILD_UNITTESTS=ON
        -DCMAKE_CXX_FLAGS="-Werror -fdiagnostics-color=always"
        -DACTS_BUILD_DIGITIZATION_PLUGIN=on
        -DACTS_BUILD_IDENTIFICATION_PLUGIN=on
        -DACTS_BUILD_JSON_PLUGIN=on
        -DACTS_BUILD_BENCHMARKS=on
        -DACTS_BUILD_FATRAS=on
        -DACTS_BUILD_EXAMPLES=on
        -DACTS_BUILD_UNITTESTS=on
        -DACTS_BUILD_LEGACY=on
        -DACTS_BUILD_DD4HEP_PLUGIN=on
        -DACTS_BUILD_TGEO_PLUGIN=on
        -DACTS_BUILD_INTEGRATIONTESTS=on
        && cmake --build . -- -j$(nproc)
        && cmake --build . -- test
        && cmake --build . -- integrationtests

  build_debug:
    runs-on: ubuntu-18.04
    container: gitlab-registry.cern.ch/acts/machines/ubuntu1910
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: >
        mkdir build && cd build
        && cmake ..
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_CXX_STANDARD=17
        -DACTS_BUILD_UNITTESTS=ON
        -DCMAKE_CXX_FLAGS="-Werror -fdiagnostics-color=always"
        -DACTS_BUILD_DIGITIZATION_PLUGIN=on
        -DACTS_BUILD_IDENTIFICATION_PLUGIN=on
        -DACTS_BUILD_JSON_PLUGIN=on
        -DACTS_BUILD_BENCHMARKS=on
        -DACTS_BUILD_FATRAS=on
        -DACTS_BUILD_EXAMPLES=on
        -DACTS_BUILD_UNITTESTS=on
        -DACTS_BUILD_LEGACY=on
        -DACTS_BUILD_DD4HEP_PLUGIN=on
        -DACTS_BUILD_TGEO_PLUGIN=on
        -DACTS_BUILD_INTEGRATIONTESTS=off
        && cmake --build . -- -j$(nproc)
        && cmake --build . -- test
